function(require_contains content expected description)
    string(FIND "${content}" "${expected}" position)
    if (position EQUAL -1)
        message(FATAL_ERROR "Missing ${description}: ${expected}")
    endif()
endfunction()

function(require_absent content forbidden description)
    string(FIND "${content}" "${forbidden}" position)
    if (NOT position EQUAL -1)
        message(FATAL_ERROR "Found forbidden ${description}: ${forbidden}")
    endif()
endfunction()

file(READ "${SOURCE_DIR}/src/providers/provider_gateway.cpp" provider_source)
file(READ "${SOURCE_DIR}/src/providers/provider_gateway.h" provider_header)
require_absent("${provider_source}" "body=%1" "provider response-body diagnostic")
require_absent("${provider_source}" "sanitizedResponseBody" "response-body sanitizer that still logs private output")
require_absent("${provider_source}" "reply->errorString()" "raw provider transport diagnostic")
require_absent("${provider_source}" "const QByteArray fileBytes = file.readAll()" "whole-file Gemini upload buffering")
require_contains("${provider_source}" "performDeviceRequest(manager, uploadRequest, &file)" "streamed Gemini upload")
require_contains("${provider_header}" "enum class ProviderDeliveryOutcome" "typed provider delivery outcome")
require_contains("${provider_header}" "OutcomeUnknown" "unknown provider delivery outcome")
require_contains("${provider_header}" "Cancelled" "cancelled provider delivery outcome")
require_contains("${provider_source}" "makeGenerationFailureResponse(request, apiResult)" "generation failure classification")
require_absent("${provider_source}" "attempt < 2" "automatic generation retry loop")
require_contains("${provider_source}" "classifyDelivery(result, method == \"POST\")" "shared delivery classifier")
require_contains("${provider_source}" "Trying again could duplicate provider work or usage." "ambiguous outcome warning")
require_absent("${provider_source}" "Idempotency-Key" "undocumented provider idempotency header")

file(READ "${SOURCE_DIR}/src/services/model_catalog_manager.cpp" catalog_source)
require_absent("${catalog_source}" "reply->errorString()" "raw catalog transport diagnostic")
require_absent("${catalog_source}" "shortResponseBody" "catalog response-body diagnostic")
require_contains("${catalog_source}" "generation != m_generation" "stale catalog generation guard")

file(READ "${SOURCE_DIR}/android/src/com/aimeetingtable/mobile/FileBridge.java" file_bridge_source)
file(READ "${SOURCE_DIR}/android/src/com/aimeetingtable/mobile/AttachmentContentProvider.java" attachment_provider_source)
file(READ "${SOURCE_DIR}/android/AndroidManifest.xml" android_manifest)
file(READ "${SOURCE_DIR}/android/src/com/aimeetingtable/mobile/BoundedStreamCopier.java" stream_copier_source)
require_contains("${android_manifest}" "android:label=\"Synsemble\"" "Synsemble Android application label")
require_contains("${android_manifest}" "android:versionName=\"1.1\"" "Synsemble Android version name")
require_contains("${android_manifest}" "android:versionCode=\"5\"" "Synsemble Android version code")
require_absent("${android_manifest}" "android:label=\"AI Meeting Table\"" "legacy Android application label")
require_contains("${file_bridge_source}" "IMPORT_EXECUTOR.submit" "background Android attachment executor")
require_contains("${file_bridge_source}" "resolver.openInputStream(uri)" "Android content-provider stream")
require_contains("${file_bridge_source}" "cancelImport" "Android attachment cancellation")
require_contains("${file_bridge_source}" "lastProgressNanos" "Android no-progress watchdog")
require_absent("${file_bridge_source}" "public static String importUriToPrivateFile" "legacy synchronous string import result")
require_contains("${file_bridge_source}" "Intent.FLAG_GRANT_READ_URI_PERMISSION" "temporary attachment read grant")
require_contains("${file_bridge_source}" "AttachmentContentProvider.register" "protected attachment content URI")
require_absent("${file_bridge_source}" "Uri.fromFile" "raw attachment file URI")
require_contains("${attachment_provider_source}" "context.getDataDir().getCanonicalFile()" "private storage boundary")
require_contains("${attachment_provider_source}" "ParcelFileDescriptor.MODE_READ_ONLY" "read-only attachment descriptor")
require_contains("${android_manifest}" "android:exported=\"false\"" "non-exported attachment provider")
require_contains("${android_manifest}" "android:grantUriPermissions=\"true\"" "attachment URI grants")
require_contains("${android_manifest}" "android:windowSoftInputMode=\"adjustResize\"" "resizing soft-keyboard behavior")
require_contains("${android_manifest}" "android:enableOnBackInvokedCallback=\"false\"" "Qt key-event Back dispatch compatibility")
require_contains("${stream_copier_source}" "MAX_ATTACHMENT_BYTES = 25L * 1024L * 1024L" "25 MiB attachment limit")
require_contains("${stream_copier_source}" "FREE_SPACE_RESERVE_BYTES = 64L * 1024L * 1024L" "64 MiB free-space reserve")
require_contains("${stream_copier_source}" "NO_PROGRESS_TIMEOUT_NANOS = 60L * 1_000_000_000L" "60-second no-progress deadline")
require_contains("${stream_copier_source}" "copied > limits.maximumBytes - read" "authoritative streaming byte limit")
require_contains("${stream_copier_source}" "finalName + \".part\"" "partial attachment destination")
require_contains("${stream_copier_source}" "digest.update(buffer, 0, read)" "incremental attachment hashing")
require_contains("${stream_copier_source}" "StandardCopyOption.ATOMIC_MOVE" "atomic attachment finalization")

file(READ "${SOURCE_DIR}/src/services/attachment_import_manager.cpp" import_manager_source)
require_contains("${import_manager_source}" "QThread::create" "dedicated C++ attachment worker")
require_contains("${import_manager_source}" "QCryptographicHash::Sha256" "incremental local attachment hashing")
file(READ "${SOURCE_DIR}/src/app/mobile_app_controller.cpp" controller_source)
file(READ "${SOURCE_DIR}/src/app/mobile_app_controller.h" controller_header)
require_absent("${controller_source}" "importAttachmentToPrivateStorage" "legacy controller-thread attachment copy")
require_contains("${controller_source}" "result.sha256, result.byteCount" "precomputed attachment metadata handoff")
require_absent("${controller_header}" "Q_INVOKABLE QString apiKey" "credential-returning QML API")
require_absent("${controller_header}" "createTable(const QString &title, int seatCount)" "initial-seat controller argument")
require_absent("${controller_source}" "Saved: %1" "stored credential preview")

file(READ "${SOURCE_DIR}/qml/Main.qml" main_qml_source)
file(GLOB qml_files "${SOURCE_DIR}/qml/*.qml")
file(GLOB_RECURSE test_qml_files "${SOURCE_DIR}/tests/*.qml")
if(test_qml_files)
    message(FATAL_ERROR "Keep QML fixtures as .qml.in templates so Android deployment does not scan QtTest")
endif()
foreach(qml_file IN LISTS qml_files)
    file(READ "${qml_file}" qml_content)
    string(TOLOWER "${qml_content}" lowercase_qml)
    require_absent("${lowercase_qml}" "ai meeting table" "legacy user-facing branding")
    if(NOT qml_file STREQUAL "${SOURCE_DIR}/qml/Main.qml")
        string(APPEND main_qml_source "\n${qml_content}")
    endif()
endforeach()
require_contains("${main_qml_source}" "title: \"Synsemble\"" "Synsemble window title")
require_absent("${main_qml_source}" "title: \"AI Meeting Table\"" "legacy window title")
require_contains("${main_qml_source}" "providerCard.catalogStatus.message" "model-refresh status binding")
require_absent("${main_qml_source}" "modelStatusRow.modelData.status" "stale model-refresh status binding")
require_contains("${main_qml_source}" "saveSeat(root.editingSeatIndex, true" "active default for agent saving")
require_absent("${main_qml_source}" "Seat is occupied" "obsolete occupancy UI")
require_contains("${main_qml_source}" "Use the attachment button beside the message composer." "single attachment import guidance")
require_contains("${main_qml_source}" "hasCredential(providerCard.index) ? \"Saved\" : \"Not saved\"" "non-secret credential status")
require_contains("${main_qml_source}" "parent: Overlay.overlay" "window-relative seat dialog positioning")
require_absent("${main_qml_source}" "Initial seats" "initial-seat table control")
require_absent("${main_qml_source}" "createSeats" "initial-seat dialog state")
require_absent("${main_qml_source}" "apiKeyStatus" "masked credential status API")
require_absent("${main_qml_source}" "Max total cost" "user-facing monetary limit")
require_absent("${main_qml_source}" "Cost estimate" "user-facing monetary telemetry")
require_absent("${main_qml_source}" "Unavailable / $" "unavailable monetary telemetry")
require_contains("${main_qml_source}" "tokenBreakdownKnown === false ? \"Unavailable\"" "unknown legacy token breakdown handling")

file(READ "${SOURCE_DIR}/src/services/budget_manager.cpp" budget_source)
require_absent("${budget_source}" "state.usedCost >=" "monetary execution hard stop")
require_contains("${budget_source}" "BudgetLimitAction::PromptToContinue, \"The maximum phase token limit" "phase token continuation pause")
require_absent("${provider_source}" "PricePerInputToken" "provider price table")
require_absent("${provider_source}" "estimatedCost" "provider monetary estimate")

file(READ "${SOURCE_DIR}/src/core/session_runner.cpp" session_runner_source)
require_contains("${session_runner_source}" "state.continuationCommand = resumeCommand" "persisted continuation command")
require_contains("${session_runner_source}" "deferredEventCommand(session, EventType::TurnCompleted" "post-response workflow deferral")
require_absent("${session_runner_source}" "Continuation will be requested after this phase" "phase advance after a hard stop")

file(READ "${SOURCE_DIR}/src/core/startup_timeline.cpp" startup_timeline_source)
require_contains("${startup_timeline_source}" "AMT_STARTUP stage=%1 elapsed_ms=%2" "numeric-only startup marker format")
require_contains("${startup_timeline_source}" "reportFullyDrawn" "Android fully-drawn report")
require_contains("${startup_timeline_source}" "m_fullyDrawnReported" "one-shot fully-drawn guard")
require_contains("${startup_timeline_source}" "AMT_STARTUP_TIMELINE" "opt-in Release startup diagnostics")

file(READ "${SOURCE_DIR}/CMakeLists.txt" cmake_source)
require_contains("${cmake_source}" "project(Synsemble VERSION 1.1" "Synsemble CMake product metadata")
require_contains("${cmake_source}" "com.aimeetingtable.myapp" "preserved Android application ID")
require_contains("${cmake_source}" "QT_ANDROID_VERSION_CODE 5" "Synsemble CMake Android version code")
require_contains("${cmake_source}" "QT_ANDROID_MIN_SDK_VERSION 28" "Qt Android minimum SDK")
require_absent("${cmake_source}" "QT_ANDROID_MIN_SDK_VERSION 26" "obsolete Qt Android minimum SDK")
require_contains("${cmake_source}" "b71f1470962019bd89534a2919f5925f93bc5779" "pinned OpenSSL commit")
require_contains("${cmake_source}" "SHA256=6c1dfff0af367bba2f2c2a27f1c2061019537524dc7892ee8efbdc8e1c6224fa" "pinned OpenSSL archive hash")
require_contains("${cmake_source}" "EXCLUDE_BY_TYPE qmltooling" "Release QML tooling exclusion")

file(READ "${SOURCE_DIR}/docs/index.html" privacy_page)
require_contains("${privacy_page}" "<title>Synsemble Privacy Policy</title>" "public Synsemble privacy branding")
string(TOLOWER "${privacy_page}" privacy_page_lower)
require_absent("${privacy_page_lower}" "ai meeting table" "stale public privacy branding")
require_absent("${privacy_page_lower}" "<script" "unexpected privacy-site scripts")
file(READ "${SOURCE_DIR}/.github/workflows/privacy-pages.yml" privacy_workflow)
require_contains("${privacy_workflow}" "cp docs/index.html" "privacy-page-only deployment staging")
require_contains("${privacy_workflow}" "path: \${{ runner.temp }}/privacy-site" "isolated Pages artifact directory")

file(GLOB_RECURSE source_files LIST_DIRECTORIES false
    "${SOURCE_DIR}/src/*"
    "${SOURCE_DIR}/android/*"
    "${SOURCE_DIR}/qml/*"
    "${SOURCE_DIR}/tests/*"
    "${SOURCE_DIR}/CMakeLists.txt"
)
foreach(path IN LISTS source_files)
    if (path MATCHES "\\.(jks|keystore|p12|pfx|pem)$" OR path MATCHES "key\\.properties$")
        message(FATAL_ERROR "Signing material is present in source: ${path}")
    endif()
endforeach()
